# ----- build/test -----
build_and_test_template: &BUILD_AND_TEST_TEMPLATE
  skip: "changesIncludeOnly('doc/*')"
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get ./...
  build_script: go build ./...
  test_script: go test ./...

task:
  name: test linux/x86_64
  alias: test_linux_x86
  container:
    image: golang:1.20-bullseye
  install_script: apt update && apt install -y libglib2.0-dev
  << : *BUILD_AND_TEST_TEMPLATE

task:
  name: test linux/arm64
  alias: test_linux_arm
  arm_container:
    image: golang:1.20-bullseye
  install_script: apt update && apt install -y libglib2.0-dev
  << : *BUILD_AND_TEST_TEMPLATE

task:
  name: test darwin/arm64
  alias: test_darwin_arm
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  install_script: brew install go@1.20
  << : *BUILD_AND_TEST_TEMPLATE

task:
  name: test freebsd-13.1/x86_64
  alias: test_freebsd-13-1_x86
  freebsd_instance:
    image_family: freebsd-13-1
  install_script: pkg install -y go glib pkgconf
  << : *BUILD_AND_TEST_TEMPLATE

# ----- lint -----

run_linter_template: &RUN_LINTER_TEMPLATE
  skip: "changesIncludeOnly('doc/*')"
  install_staticcheck_script: go install honnef.co/go/tools/cmd/staticcheck@2023.1
  run_script: staticcheck -f text ./...

task:
  name: lint linux
  alias: lint_linux
  container:
    image: golang:1.20-bullseye
  install_script: apt update && apt install -y libglib2.0-dev
  << : *RUN_LINTER_TEMPLATE

task:
  name: lint darwin
  alias: lint_darwin
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  install_script: brew install go@1.20
  << : *RUN_LINTER_TEMPLATE

task:
  name: lint freebsd
  alias: lint_freebsd
  freebsd_instance:
    image_family: freebsd-13-1
  install_script: pkg install -y go glib pkgconf
  << : *RUN_LINTER_TEMPLATE
