# ----- build/test/lint -----
build_test_lint_template: &BUILD_TEST_LINT_TEMPLATE
  skip: "changesIncludeOnly('doc/*')"
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  install_staticcheck_script: go install honnef.co/go/tools/cmd/staticcheck@2023.1
  go_get_script: go get
  build_script: go build
  test_script: |
    (
      ./support/is-not-cross-compiling.sh && \
      go test ./...
    ) || :
  lint_script: |
    (
      ./support/is-not-cross-compiling.sh && \
      $(go env GOPATH)/bin/staticcheck -f text ./...
    ) || :

env:
  GITHUB_TOKEN: ENCRYPTED[47866e8d4af465980beac1af5ac3da3eef4c05bf386b74a115b03dab368a96dae31330a3274c9196a2dcd2354921e9f1]

task:
  name: linux/x86_64
  container:
    image: golang:1.21-bullseye
  install_script: apt update && apt install -y libglib2.0-dev
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_linux_x86_86"

task:
  name: linux/arm64
  arm_container:
    image: golang:1.21-bullseye
  install_script: apt update && apt install -y libglib2.0-dev
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_linux_arm64"

task:
  name: darwin/amd64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  install_script: brew install go@1.21
  env:
    GOARCH: amd64
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_darwin_amd64"

task:
  name: darwin/arm64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  install_script: brew install go@1.21
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_darwin_arm64"

task:
  name: freebsd-13.1/x86_64
  freebsd_instance:
    image_family: freebsd-13-1
  install_script: pkg install -y bash go glib pkgconf
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_freebsd_amd64"
