# ----- build/test -----
build_test_lint_template: &BUILD_TEST_LINT_TEMPLATE
  skip: "changesIncludeOnly('doc/*')"
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  install_staticcheck_script: go install honnef.co/go/tools/cmd/staticcheck@2023.1
  go_get_script: go env GOARCH && go get ./...
  build_script: go env GOARCH && go build ./...
  test_script: go env GOARCH && go test ./...
  lint_script: go env GOARCH && $(go env GOPATH)/bin/staticcheck -f text ./...

task:
  name: test linux/x86_64
  alias: linux_x86
  container:
    image: golang:1.20-bullseye
  install_script: apt update && apt install -y libglib2.0-dev
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_linux_x86_86"

task:
  name: test linux/arm64
  alias: linux_arm
  arm_container:
    image: golang:1.20-bullseye
  install_script: apt update && apt install -y libglib2.0-dev
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_linux_arm64"

task:
  name: test darwin/amd64
  alias: darwin_x86
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  install_script: brew install go@1.20
  env:
    GOARCH: amd64
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_darwin_amd64"

task:
  name: test darwin/arm64
  alias: darwin_arm
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  install_script: brew install go@1.20
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_darwin_arm64"

task:
  name: test freebsd-13.1/x86_64
  alias: freebsd-13-1_x86
  freebsd_instance:
    image_family: freebsd-13-1
  install_script: pkg install -y bash go glib pkgconf
  << : *BUILD_TEST_LINT_TEMPLATE
  publish_script: ./support/maybe-upload-artifact.sh "thcon_freebsd_amd64"
