{
  name: "go check",
  on: {
    push: {
      branches: [
        "$default-branch",
        "go-port",
        "go/**",
      ],
    },
    pull_request: {
      branches: [
        "$default-branch",
        "go-port",
        "go/**",
      ],
    },
  },
  jobs: {
    build: {
      "runs-on": "ubuntu-latest",
      steps: [
        { uses: "actions/checkout@v2" },
        {
          name: "Set up Go",
          uses: "actions/setup-go@v2",
          with: {
            "go-version": "1.17",
          },
        },
        {
          name: "Build",
          run: "go build -v ./...",
        },
        {
          name: "Lint",
          uses: "golangci/golangci-lint-action@3.1.0",
        },
        {
          name: "Test",
          run: "go test -v ./...",
        },
      ],
    },
  },
}
